name: supabase-smoke

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: REST ping (anon)
        run: |
          set -e
          echo "Pinging Supabase project at https://iowbsmmpuksltenbgtww.supabase.co ..."
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvd2JzbW1wdWtzbHRlbmJndHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjg5MTQsImV4cCI6MjA3NjY0NDkxNH0.PfmsykX8hPra4K5bOE1n0ZyWD1rGsUNvOZUiYpbsKdE" \
            "https://iowbsmmpuksltenbgtww.supabase.co/auth/v1/health")
          echo "HTTP=$code"
          test "$code" -ge 200 -a "$code" -lt 500
