name: supabase-smoke

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sanity check secrets are set
        run: |
          set -e
          if [ -z "${{ secrets.SUPABASE_PROJECT_URL }}" ]; then
            echo "SUPABASE_PROJECT_URL is empty"; exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_ANON_PUBLIC_KEY }}" ]; then
            echo "SUPABASE_ANON_PUBLIC_KEY is empty"; exit 1
          fi
          case "${{ secrets.SUPABASE_PROJECT_URL }}" in
            https://*.supabase.co) echo "URL format OK";;
            *) echo "URL must look like https://<ref>.supabase.co"; exit 2;;
          esac

      - name: REST ping (anon)
        run: |
          set -e
          URL="${{ secrets.SUPABASE_PROJECT_URL }}/auth/v1/health"
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_PUBLIC_KEY }}" \
            "$URL")
          echo "HTTP=$code"
          test "$code" -ge 200 -a "$code" -lt 500
