name: supabase-smoke

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: REST ping (anon)
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}\n" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_PUBLIC_KEY }}" \
            "${{ secrets.SUPABASE_PROJECT_URL }}/rest/v1/")
          echo "HTTP=$code"
          test "$code" -ge 200 -a "$code" -lt 500
