name: secret-leak-guard

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Run GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for diffs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose --redact --source .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
